---

- name: Install System Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - libpq-dev
    - git

- name: Clone Django Repository
  git: repo=https://github.com/cewing/djangoblog_uwpce.git dest={{ django_home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"
